version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    restart: always
  backend:
    env_file: .env
    image: shpindik/kittygram_backend
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
    depends_on:
      - db
    restart: always
  frontend:
    env_file: .env
    image: shpindik/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
    depends_on:
      - backend
    restart: always
  gateway:
    env_file: .env
    image: shpindik/kittygram_gateway
    ports:
      - 9000:80
    volumes:
      - static_volume:/staticfiles
      - media_volume:/media
    depends_on:
      - backend
      - frontend
    restart: always
